# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diptera_track.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1124, 674))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.ses_par_tab = QtWidgets.QWidget()
        self.ses_par_tab.setObjectName("ses_par_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ses_par_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.ses_par_tab)
        self.widget.setMinimumSize(QtCore.QSize(0, 551))
        self.widget.setObjectName("widget")
        self.folder_select_tree = QtWidgets.QTreeView(self.widget)
        self.folder_select_tree.setGeometry(QtCore.QRect(9, 30, 571, 321))
        self.folder_select_tree.setMinimumSize(QtCore.QSize(451, 0))
        self.folder_select_tree.setObjectName("folder_select_tree")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(9, 9, 128, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(600, 0, 124, 16))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(590, 20, 511, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(600, 30, 91, 16))
        self.label_2.setObjectName("label_2")
        self.ses_folder_label = QtWidgets.QLabel(self.widget)
        self.ses_folder_label.setGeometry(QtCore.QRect(620, 50, 471, 20))
        self.ses_folder_label.setObjectName("ses_folder_label")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(600, 90, 141, 16))
        self.label_5.setObjectName("label_5")
        self.bckg_folder_label = QtWidgets.QLabel(self.widget)
        self.bckg_folder_label.setGeometry(QtCore.QRect(620, 110, 281, 20))
        self.bckg_folder_label.setObjectName("bckg_folder_label")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(580, 30, 20, 561))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(600, 130, 291, 16))
        self.label_7.setObjectName("label_7")
        self.cal_folder_label = QtWidgets.QLabel(self.widget)
        self.cal_folder_label.setGeometry(QtCore.QRect(620, 150, 381, 20))
        self.cal_folder_label.setObjectName("cal_folder_label")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(600, 200, 291, 16))
        self.label_9.setObjectName("label_9")
        self.mov_folder1_label = QtWidgets.QLabel(self.widget)
        self.mov_folder1_label.setGeometry(QtCore.QRect(620, 220, 371, 20))
        self.mov_folder1_label.setObjectName("mov_folder1_label")
        self.mov_folder2_label = QtWidgets.QLabel(self.widget)
        self.mov_folder2_label.setGeometry(QtCore.QRect(620, 240, 371, 20))
        self.mov_folder2_label.setObjectName("mov_folder2_label")
        self.mov_folder3_label = QtWidgets.QLabel(self.widget)
        self.mov_folder3_label.setGeometry(QtCore.QRect(620, 260, 371, 20))
        self.mov_folder3_label.setObjectName("mov_folder3_label")
        self.mov_folder4_label = QtWidgets.QLabel(self.widget)
        self.mov_folder4_label.setGeometry(QtCore.QRect(620, 280, 371, 20))
        self.mov_folder4_label.setObjectName("mov_folder4_label")
        self.mov_folder5_label = QtWidgets.QLabel(self.widget)
        self.mov_folder5_label.setGeometry(QtCore.QRect(620, 300, 371, 20))
        self.mov_folder5_label.setObjectName("mov_folder5_label")
        self.mov_folder6_label = QtWidgets.QLabel(self.widget)
        self.mov_folder6_label.setGeometry(QtCore.QRect(620, 320, 371, 20))
        self.mov_folder6_label.setObjectName("mov_folder6_label")
        self.mov_folder7_label = QtWidgets.QLabel(self.widget)
        self.mov_folder7_label.setGeometry(QtCore.QRect(620, 340, 371, 20))
        self.mov_folder7_label.setObjectName("mov_folder7_label")
        self.mov_folder8_label = QtWidgets.QLabel(self.widget)
        self.mov_folder8_label.setGeometry(QtCore.QRect(620, 360, 371, 20))
        self.mov_folder8_label.setObjectName("mov_folder8_label")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(600, 390, 301, 20))
        self.label_18.setObjectName("label_18")
        self.cam_folder1_label = QtWidgets.QLabel(self.widget)
        self.cam_folder1_label.setGeometry(QtCore.QRect(620, 410, 371, 20))
        self.cam_folder1_label.setObjectName("cam_folder1_label")
        self.cam_folder2_label = QtWidgets.QLabel(self.widget)
        self.cam_folder2_label.setGeometry(QtCore.QRect(620, 430, 371, 20))
        self.cam_folder2_label.setObjectName("cam_folder2_label")
        self.cam_folder3_label = QtWidgets.QLabel(self.widget)
        self.cam_folder3_label.setGeometry(QtCore.QRect(620, 450, 371, 20))
        self.cam_folder3_label.setObjectName("cam_folder3_label")
        self.cam_folder4_label = QtWidgets.QLabel(self.widget)
        self.cam_folder4_label.setGeometry(QtCore.QRect(620, 470, 371, 20))
        self.cam_folder4_label.setObjectName("cam_folder4_label")
        self.ses_folder_rbtn = QtWidgets.QRadioButton(self.widget)
        self.ses_folder_rbtn.setGeometry(QtCore.QRect(600, 50, 21, 21))
        self.ses_folder_rbtn.setObjectName("ses_folder_rbtn")
        self.bckg_folder_rbtn = QtWidgets.QRadioButton(self.widget)
        self.bckg_folder_rbtn.setGeometry(QtCore.QRect(600, 110, 21, 21))
        self.bckg_folder_rbtn.setObjectName("bckg_folder_rbtn")
        self.cal_folder_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cal_folder_rbtn.setGeometry(QtCore.QRect(600, 150, 21, 21))
        self.cal_folder_rbtn.setObjectName("cal_folder_rbtn")
        self.mov_folder1_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder1_rbtn.setGeometry(QtCore.QRect(600, 220, 21, 21))
        self.mov_folder1_rbtn.setObjectName("mov_folder1_rbtn")
        self.mov_folder2_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder2_rbtn.setGeometry(QtCore.QRect(600, 240, 21, 21))
        self.mov_folder2_rbtn.setObjectName("mov_folder2_rbtn")
        self.mov_folder3_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder3_rbtn.setGeometry(QtCore.QRect(600, 260, 21, 21))
        self.mov_folder3_rbtn.setObjectName("mov_folder3_rbtn")
        self.mov_folder4_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder4_rbtn.setGeometry(QtCore.QRect(600, 280, 21, 21))
        self.mov_folder4_rbtn.setObjectName("mov_folder4_rbtn")
        self.mov_folder5_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder5_rbtn.setGeometry(QtCore.QRect(600, 300, 21, 21))
        self.mov_folder5_rbtn.setObjectName("mov_folder5_rbtn")
        self.mov_folder6_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder6_rbtn.setGeometry(QtCore.QRect(600, 320, 21, 21))
        self.mov_folder6_rbtn.setObjectName("mov_folder6_rbtn")
        self.mov_folder7_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder7_rbtn.setGeometry(QtCore.QRect(600, 340, 21, 21))
        self.mov_folder7_rbtn.setObjectName("mov_folder7_rbtn")
        self.mov_folder8_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mov_folder8_rbtn.setGeometry(QtCore.QRect(600, 360, 21, 21))
        self.mov_folder8_rbtn.setObjectName("mov_folder8_rbtn")
        self.cam_folder1_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cam_folder1_rbtn.setGeometry(QtCore.QRect(600, 410, 21, 21))
        self.cam_folder1_rbtn.setObjectName("cam_folder1_rbtn")
        self.cam_folder2_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cam_folder2_rbtn.setGeometry(QtCore.QRect(600, 430, 21, 21))
        self.cam_folder2_rbtn.setObjectName("cam_folder2_rbtn")
        self.cam_folder3_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cam_folder3_rbtn.setGeometry(QtCore.QRect(600, 450, 21, 21))
        self.cam_folder3_rbtn.setObjectName("cam_folder3_rbtn")
        self.cam_folder4_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cam_folder4_rbtn.setGeometry(QtCore.QRect(600, 470, 21, 21))
        self.cam_folder4_rbtn.setObjectName("cam_folder4_rbtn")
        self.cam_folder5_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cam_folder5_rbtn.setGeometry(QtCore.QRect(600, 490, 21, 21))
        self.cam_folder5_rbtn.setObjectName("cam_folder5_rbtn")
        self.cam_folder6_rbtn = QtWidgets.QRadioButton(self.widget)
        self.cam_folder6_rbtn.setGeometry(QtCore.QRect(600, 510, 21, 21))
        self.cam_folder6_rbtn.setObjectName("cam_folder6_rbtn")
        self.cam_folder5_label = QtWidgets.QLabel(self.widget)
        self.cam_folder5_label.setGeometry(QtCore.QRect(620, 490, 371, 20))
        self.cam_folder5_label.setObjectName("cam_folder5_label")
        self.cam_folder6_label = QtWidgets.QLabel(self.widget)
        self.cam_folder6_label.setGeometry(QtCore.QRect(620, 510, 371, 20))
        self.cam_folder6_label.setObjectName("cam_folder6_label")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setGeometry(QtCore.QRect(600, 540, 201, 16))
        self.label_25.setObjectName("label_25")
        self.frame_name_rbtn = QtWidgets.QRadioButton(self.widget)
        self.frame_name_rbtn.setGeometry(QtCore.QRect(600, 560, 21, 21))
        self.frame_name_rbtn.setObjectName("frame_name_rbtn")
        self.frame_name_label = QtWidgets.QLabel(self.widget)
        self.frame_name_label.setGeometry(QtCore.QRect(620, 560, 391, 20))
        self.frame_name_label.setObjectName("frame_name_label")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setGeometry(QtCore.QRect(930, 80, 161, 20))
        self.label_27.setObjectName("label_27")
        self.bck_img_fmt_box = QtWidgets.QComboBox(self.widget)
        self.bck_img_fmt_box.setGeometry(QtCore.QRect(1020, 100, 79, 23))
        self.bck_img_fmt_box.setObjectName("bck_img_fmt_box")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setGeometry(QtCore.QRect(930, 130, 161, 20))
        self.label_28.setObjectName("label_28")
        self.cal_img_fmt_box = QtWidgets.QComboBox(self.widget)
        self.cal_img_fmt_box.setGeometry(QtCore.QRect(1020, 150, 79, 23))
        self.cal_img_fmt_box.setObjectName("cal_img_fmt_box")
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setGeometry(QtCore.QRect(970, 540, 131, 20))
        self.label_29.setObjectName("label_29")
        self.frame_img_fmt_box = QtWidgets.QComboBox(self.widget)
        self.frame_img_fmt_box.setGeometry(QtCore.QRect(1020, 560, 79, 23))
        self.frame_img_fmt_box.setObjectName("frame_img_fmt_box")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(10, 460, 571, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(10, 580, 1091, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setGeometry(QtCore.QRect(250, 470, 151, 16))
        self.label_30.setObjectName("label_30")
        self.start_frame_spin = QtWidgets.QSpinBox(self.widget)
        self.start_frame_spin.setGeometry(QtCore.QRect(120, 490, 91, 24))
        self.start_frame_spin.setObjectName("start_frame_spin")
        self.label_31 = QtWidgets.QLabel(self.widget)
        self.label_31.setGeometry(QtCore.QRect(10, 490, 101, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.widget)
        self.label_32.setGeometry(QtCore.QRect(10, 520, 101, 16))
        self.label_32.setObjectName("label_32")
        self.trig_frame_spin = QtWidgets.QSpinBox(self.widget)
        self.trig_frame_spin.setGeometry(QtCore.QRect(120, 520, 91, 24))
        self.trig_frame_spin.setObjectName("trig_frame_spin")
        self.label_33 = QtWidgets.QLabel(self.widget)
        self.label_33.setGeometry(QtCore.QRect(10, 550, 101, 16))
        self.label_33.setObjectName("label_33")
        self.end_frame_spin = QtWidgets.QSpinBox(self.widget)
        self.end_frame_spin.setGeometry(QtCore.QRect(120, 550, 91, 24))
        self.end_frame_spin.setObjectName("end_frame_spin")
        self.label_34 = QtWidgets.QLabel(self.widget)
        self.label_34.setGeometry(QtCore.QRect(250, 490, 91, 16))
        self.label_34.setObjectName("label_34")
        self.trig_mode_box = QtWidgets.QComboBox(self.widget)
        self.trig_mode_box.setGeometry(QtCore.QRect(350, 490, 111, 23))
        self.trig_mode_box.setObjectName("trig_mode_box")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(10, 350, 571, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(250, 360, 101, 16))
        self.label_4.setObjectName("label_4")
        self.mdl_loc_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mdl_loc_rbtn.setGeometry(QtCore.QRect(10, 400, 21, 21))
        self.mdl_loc_rbtn.setObjectName("mdl_loc_rbtn")
        self.mdl_loc_label = QtWidgets.QLabel(self.widget)
        self.mdl_loc_label.setGeometry(QtCore.QRect(40, 400, 541, 21))
        self.mdl_loc_label.setObjectName("mdl_loc_label")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(10, 380, 171, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(10, 420, 141, 16))
        self.label_11.setObjectName("label_11")
        self.mdl_name_rbtn = QtWidgets.QRadioButton(self.widget)
        self.mdl_name_rbtn.setGeometry(QtCore.QRect(10, 440, 21, 21))
        self.mdl_name_rbtn.setObjectName("mdl_name_rbtn")
        self.mdl_name_label = QtWidgets.QLabel(self.widget)
        self.mdl_name_label.setGeometry(QtCore.QRect(40, 440, 541, 21))
        self.mdl_name_label.setObjectName("mdl_name_label")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(600, 170, 101, 16))
        self.label_6.setObjectName("label_6")
        self.cal_file_label = QtWidgets.QLabel(self.widget)
        self.cal_file_label.setGeometry(QtCore.QRect(710, 170, 291, 20))
        self.cal_file_label.setObjectName("cal_file_label")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(600, 70, 101, 16))
        self.label_8.setObjectName("label_8")
        self.ses_name_label = QtWidgets.QLabel(self.widget)
        self.ses_name_label.setGeometry(QtCore.QRect(700, 70, 381, 20))
        self.ses_name_label.setObjectName("ses_name_label")
        self.reset_selection_push_btn = QtWidgets.QPushButton(self.widget)
        self.reset_selection_push_btn.setGeometry(QtCore.QRect(470, 0, 101, 23))
        self.reset_selection_push_btn.setObjectName("reset_selection_push_btn")
        self.start_session_push_btn = QtWidgets.QPushButton(self.widget)
        self.start_session_push_btn.setGeometry(QtCore.QRect(1010, 600, 85, 23))
        self.start_session_push_btn.setObjectName("start_session_push_btn")
        self.save_settings_push_btn = QtWidgets.QPushButton(self.widget)
        self.save_settings_push_btn.setGeometry(QtCore.QRect(870, 600, 131, 23))
        self.save_settings_push_btn.setObjectName("save_settings_push_btn")
        self.load_settings_file_label = QtWidgets.QLabel(self.widget)
        self.load_settings_file_label.setGeometry(QtCore.QRect(40, 600, 671, 21))
        self.load_settings_file_label.setObjectName("load_settings_file_label")
        self.load_settings_push_btn = QtWidgets.QPushButton(self.widget)
        self.load_settings_push_btn.setGeometry(QtCore.QRect(720, 600, 141, 23))
        self.load_settings_push_btn.setObjectName("load_settings_push_btn")
        self.load_settings_rbtn = QtWidgets.QRadioButton(self.widget)
        self.load_settings_rbtn.setGeometry(QtCore.QRect(10, 600, 21, 21))
        self.load_settings_rbtn.setObjectName("load_settings_rbtn")
        self.verticalLayout_4.addWidget(self.widget)
        self.tabs.addTab(self.ses_par_tab, "")
        self.focal_grid_tab = QtWidgets.QWidget()
        self.focal_grid_tab.setObjectName("focal_grid_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.focal_grid_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.focal_grid_tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.line_9 = QtWidgets.QFrame(self.widget_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_7.addWidget(self.line_9, 0, 0, 2, 8)
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 1, 2, 2, 3)
        self.line_6 = QtWidgets.QFrame(self.widget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 2, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 3, 2, 1, 1)
        self.nx_spin = QtWidgets.QSpinBox(self.widget_2)
        self.nx_spin.setObjectName("nx_spin")
        self.gridLayout_7.addWidget(self.nx_spin, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(928, 213, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 3, 4, 7, 4)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 4, 2, 1, 1)
        self.ny_spin = QtWidgets.QSpinBox(self.widget_2)
        self.ny_spin.setObjectName("ny_spin")
        self.gridLayout_7.addWidget(self.ny_spin, 4, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 5, 2, 1, 1)
        self.nz_spin = QtWidgets.QSpinBox(self.widget_2)
        self.nz_spin.setObjectName("nz_spin")
        self.gridLayout_7.addWidget(self.nz_spin, 5, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 6, 2, 1, 1)
        self.ds_spin = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.ds_spin.setObjectName("ds_spin")
        self.gridLayout_7.addWidget(self.ds_spin, 6, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 7, 2, 1, 1)
        self.x0_spin = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.x0_spin.setObjectName("x0_spin")
        self.gridLayout_7.addWidget(self.x0_spin, 7, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 8, 2, 1, 1)
        self.y0_spin = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.y0_spin.setObjectName("y0_spin")
        self.gridLayout_7.addWidget(self.y0_spin, 8, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 9, 2, 1, 1)
        self.z0_spin = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.z0_spin.setObjectName("z0_spin")
        self.gridLayout_7.addWidget(self.z0_spin, 9, 3, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.widget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_7.addWidget(self.line_7, 10, 0, 1, 7)
        spacerItem1 = QtWidgets.QSpacerItem(696, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 10, 7, 2, 1)
        self.calc_vox_btn = QtWidgets.QPushButton(self.widget_2)
        self.calc_vox_btn.setObjectName("calc_vox_btn")
        self.gridLayout_7.addWidget(self.calc_vox_btn, 11, 0, 1, 4)
        self.vox_progress_bar = QtWidgets.QProgressBar(self.widget_2)
        self.vox_progress_bar.setMinimumSize(QtCore.QSize(211, 0))
        self.vox_progress_bar.setProperty("value", 24)
        self.vox_progress_bar.setObjectName("vox_progress_bar")
        self.gridLayout_7.addWidget(self.vox_progress_bar, 11, 5, 1, 2)
        self.line_8 = QtWidgets.QFrame(self.widget_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_7.addWidget(self.line_8, 12, 0, 2, 8)
        self.label_49 = QtWidgets.QLabel(self.widget_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 13, 1, 2, 6)
        spacerItem2 = QtWidgets.QSpacerItem(804, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 14, 6, 2, 2)
        self.label_50 = QtWidgets.QLabel(self.widget_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 15, 1, 1, 3)
        self.pixel_size_spin = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.pixel_size_spin.setObjectName("pixel_size_spin")
        self.gridLayout_7.addWidget(self.pixel_size_spin, 15, 4, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(1079, 267, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 16, 0, 1, 8)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.tabs.addTab(self.focal_grid_tab, "")
        self.model_scale_tab = QtWidgets.QWidget()
        self.model_scale_tab.setObjectName("model_scale_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.model_scale_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.model_scale_tab)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rawFrameView = ScaleModelWidget(self.widget_3)
        self.rawFrameView.setMinimumSize(QtCore.QSize(1091, 511))
        self.rawFrameView.setObjectName("rawFrameView")
        self.gridLayout_3.addWidget(self.rawFrameView, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setMinimumSize(QtCore.QSize(1091, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 101))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_22 = QtWidgets.QLabel(self.widget_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 0, 1, 1)
        self.scaleTable = QtWidgets.QTableWidget(self.widget_4)
        self.scaleTable.setMinimumSize(QtCore.QSize(411, 81))
        self.scaleTable.setObjectName("scaleTable")
        self.scaleTable.setColumnCount(0)
        self.scaleTable.setRowCount(0)
        self.gridLayout.addWidget(self.scaleTable, 0, 1, 4, 1)
        spacerItem4 = QtWidgets.QSpacerItem(248, 78, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 4, 1)
        self.raw_mov_spin = QtWidgets.QSpinBox(self.widget_4)
        self.raw_mov_spin.setObjectName("raw_mov_spin")
        self.gridLayout.addWidget(self.raw_mov_spin, 1, 0, 1, 1)
        self.load_scale_btn = QtWidgets.QPushButton(self.widget_4)
        self.load_scale_btn.setObjectName("load_scale_btn")
        self.gridLayout.addWidget(self.load_scale_btn, 1, 3, 2, 1)
        self.save_scale_btn = QtWidgets.QPushButton(self.widget_4)
        self.save_scale_btn.setObjectName("save_scale_btn")
        self.gridLayout.addWidget(self.save_scale_btn, 1, 4, 2, 1)
        self.raw_frame_spin = QtWidgets.QSpinBox(self.widget_4)
        self.raw_frame_spin.setObjectName("raw_frame_spin")
        self.gridLayout.addWidget(self.raw_frame_spin, 3, 0, 1, 1)
        self.set_model_btn = QtWidgets.QPushButton(self.widget_4)
        self.set_model_btn.setObjectName("set_model_btn")
        self.gridLayout.addWidget(self.set_model_btn, 1, 5, 2, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.tabs.addTab(self.model_scale_tab, "")
        self.model_view_tab = QtWidgets.QWidget()
        self.model_view_tab.setObjectName("model_view_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.model_view_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model_param_disp = QtWidgets.QWidget(self.model_view_tab)
        self.model_param_disp.setObjectName("model_param_disp")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.model_param_disp)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_23 = QtWidgets.QLabel(self.model_param_disp)
        self.label_23.setMinimumSize(QtCore.QSize(114, 621))
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.model_param_disp)
        self.model_view_window = ModelViewWidget(self.model_view_tab)
        self.model_view_window.setMinimumSize(QtCore.QSize(971, 631))
        self.model_view_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model_view_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.model_view_window.setObjectName("model_view_window")
        self.horizontalLayout.addWidget(self.model_view_window)
        self.tabs.addTab(self.model_view_tab, "")
        self.segment_tab = QtWidgets.QWidget()
        self.segment_tab.setObjectName("segment_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.segment_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.seg_view = ImageSegmentWidget(self.segment_tab)
        self.seg_view.setMinimumSize(QtCore.QSize(1101, 481))
        self.seg_view.setObjectName("seg_view")
        self.verticalLayout.addWidget(self.seg_view)
        self.seg_widget = QtWidgets.QWidget(self.segment_tab)
        self.seg_widget.setMinimumSize(QtCore.QSize(1122, 90))
        self.seg_widget.setMaximumSize(QtCore.QSize(16777215, 141))
        self.seg_widget.setObjectName("seg_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.seg_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_40 = QtWidgets.QLabel(self.seg_widget)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.seg_widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.seg_widget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.seg_widget)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.seg_widget)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 0, 4, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.seg_widget)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 0, 5, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.seg_widget)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 0, 6, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.seg_widget)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 0, 7, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.seg_widget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_5.addWidget(self.line_10, 0, 8, 4, 1)
        self.label_43 = QtWidgets.QLabel(self.seg_widget)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 0, 9, 1, 2)
        self.line_11 = QtWidgets.QFrame(self.seg_widget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_5.addWidget(self.line_11, 0, 12, 4, 1)
        spacerItem5 = QtWidgets.QSpacerItem(176, 110, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 13, 4, 1)
        spacerItem6 = QtWidgets.QSpacerItem(88, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 0, 14, 3, 1)
        self.seg_mov_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.seg_mov_spin.setObjectName("seg_mov_spin")
        self.gridLayout_5.addWidget(self.seg_mov_spin, 1, 0, 1, 1)
        self.seg_frame_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.seg_frame_spin.setObjectName("seg_frame_spin")
        self.gridLayout_5.addWidget(self.seg_frame_spin, 1, 1, 1, 1)
        self.body_thresh_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.body_thresh_spin.setObjectName("body_thresh_spin")
        self.gridLayout_5.addWidget(self.body_thresh_spin, 1, 2, 1, 1)
        self.wing_thresh_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.wing_thresh_spin.setObjectName("wing_thresh_spin")
        self.gridLayout_5.addWidget(self.wing_thresh_spin, 1, 3, 1, 1)
        self.sigma_spin = QtWidgets.QDoubleSpinBox(self.seg_widget)
        self.sigma_spin.setObjectName("sigma_spin")
        self.gridLayout_5.addWidget(self.sigma_spin, 1, 4, 1, 1)
        self.K_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.K_spin.setObjectName("K_spin")
        self.gridLayout_5.addWidget(self.K_spin, 1, 5, 1, 1)
        self.min_body_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.min_body_spin.setObjectName("min_body_spin")
        self.gridLayout_5.addWidget(self.min_body_spin, 1, 6, 1, 1)
        self.min_wing_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.min_wing_spin.setObjectName("min_wing_spin")
        self.gridLayout_5.addWidget(self.min_wing_spin, 1, 7, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.seg_widget)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 1, 9, 1, 1)
        self.mask_cam_nr_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.mask_cam_nr_spin.setObjectName("mask_cam_nr_spin")
        self.gridLayout_5.addWidget(self.mask_cam_nr_spin, 1, 10, 1, 2)
        self.label_45 = QtWidgets.QLabel(self.seg_widget)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 2, 9, 1, 1)
        self.mask_seg_nr_spin = QtWidgets.QSpinBox(self.seg_widget)
        self.mask_seg_nr_spin.setObjectName("mask_seg_nr_spin")
        self.gridLayout_5.addWidget(self.mask_seg_nr_spin, 2, 10, 1, 2)
        self.seg_update_btn = QtWidgets.QPushButton(self.seg_widget)
        self.seg_update_btn.setObjectName("seg_update_btn")
        self.gridLayout_5.addWidget(self.seg_update_btn, 3, 0, 1, 2)
        self.add_mask_btn = QtWidgets.QPushButton(self.seg_widget)
        self.add_mask_btn.setObjectName("add_mask_btn")
        self.gridLayout_5.addWidget(self.add_mask_btn, 3, 9, 1, 1)
        self.reset_mask_btn = QtWidgets.QPushButton(self.seg_widget)
        self.reset_mask_btn.setObjectName("reset_mask_btn")
        self.gridLayout_5.addWidget(self.reset_mask_btn, 3, 11, 1, 1)
        self.continue_btn = QtWidgets.QPushButton(self.seg_widget)
        self.continue_btn.setObjectName("continue_btn")
        self.gridLayout_5.addWidget(self.continue_btn, 3, 14, 1, 1)
        self.verticalLayout.addWidget(self.seg_widget)
        self.tabs.addTab(self.segment_tab, "")
        self.pcl_view_tab = QtWidgets.QWidget()
        self.pcl_view_tab.setObjectName("pcl_view_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pcl_view_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pcl_view = BBoxWidget(self.pcl_view_tab)
        self.pcl_view.setMinimumSize(QtCore.QSize(1121, 521))
        self.pcl_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pcl_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pcl_view.setObjectName("pcl_view")
        self.verticalLayout_6.addWidget(self.pcl_view)
        self.widget_5 = QtWidgets.QWidget(self.pcl_view_tab)
        self.widget_5.setMinimumSize(QtCore.QSize(1101, 111))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_41 = QtWidgets.QLabel(self.widget_5)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 0, 0, 1, 1)
        self.flight_select_btn_group = QtWidgets.QGroupBox(self.widget_5)
        self.flight_select_btn_group.setObjectName("flight_select_btn_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.flight_select_btn_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tethered_radio_btn = QtWidgets.QRadioButton(self.flight_select_btn_group)
        self.tethered_radio_btn.setObjectName("tethered_radio_btn")
        self.gridLayout_6.addWidget(self.tethered_radio_btn, 0, 0, 1, 1)
        self.free_radio_btn = QtWidgets.QRadioButton(self.flight_select_btn_group)
        self.free_radio_btn.setObjectName("free_radio_btn")
        self.gridLayout_6.addWidget(self.free_radio_btn, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.flight_select_btn_group, 0, 1, 4, 1)
        self.label_47 = QtWidgets.QLabel(self.widget_5)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 0, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_5)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(456, 90, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 4, 4, 1)
        self.view_select_group = QtWidgets.QGroupBox(self.widget_5)
        self.view_select_group.setObjectName("view_select_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.view_select_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pcl_view_btn = QtWidgets.QRadioButton(self.view_select_group)
        self.pcl_view_btn.setObjectName("pcl_view_btn")
        self.verticalLayout_3.addWidget(self.pcl_view_btn)
        self.bbox_view_btn = QtWidgets.QRadioButton(self.view_select_group)
        self.bbox_view_btn.setObjectName("bbox_view_btn")
        self.verticalLayout_3.addWidget(self.bbox_view_btn)
        self.model_view_btn = QtWidgets.QRadioButton(self.view_select_group)
        self.model_view_btn.setObjectName("model_view_btn")
        self.verticalLayout_3.addWidget(self.model_view_btn)
        self.gridLayout_8.addWidget(self.view_select_group, 0, 5, 4, 1)
        self.pcl_mov_spin = QtWidgets.QSpinBox(self.widget_5)
        self.pcl_mov_spin.setObjectName("pcl_mov_spin")
        self.gridLayout_8.addWidget(self.pcl_mov_spin, 1, 0, 1, 1)
        self.stroke_bound_spin = QtWidgets.QSpinBox(self.widget_5)
        self.stroke_bound_spin.setObjectName("stroke_bound_spin")
        self.gridLayout_8.addWidget(self.stroke_bound_spin, 1, 2, 1, 1)
        self.wing_pitch_bound_spin = QtWidgets.QSpinBox(self.widget_5)
        self.wing_pitch_bound_spin.setObjectName("wing_pitch_bound_spin")
        self.gridLayout_8.addWidget(self.wing_pitch_bound_spin, 1, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.widget_5)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.widget_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 2, 3, 1, 1)
        self.pcl_frame_spin = QtWidgets.QSpinBox(self.widget_5)
        self.pcl_frame_spin.setObjectName("pcl_frame_spin")
        self.gridLayout_8.addWidget(self.pcl_frame_spin, 3, 0, 1, 1)
        self.dev_bound_spin = QtWidgets.QSpinBox(self.widget_5)
        self.dev_bound_spin.setObjectName("dev_bound_spin")
        self.gridLayout_8.addWidget(self.dev_bound_spin, 3, 2, 1, 1)
        self.sphere_radius_spin = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.sphere_radius_spin.setObjectName("sphere_radius_spin")
        self.gridLayout_8.addWidget(self.sphere_radius_spin, 3, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.tabs.addTab(self.pcl_view_tab, "")
        self.opt_tab = QtWidgets.QWidget()
        self.opt_tab.setObjectName("opt_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.opt_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.opt_widget = QtWidgets.QWidget(self.opt_tab)
        self.opt_widget.setObjectName("opt_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.opt_widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.contour_view = ContourViewWidget(self.opt_widget)
        self.contour_view.setObjectName("contour_view")
        self.verticalLayout_8.addWidget(self.contour_view)
        self.opt_settings_widget = QtWidgets.QWidget(self.opt_widget)
        self.opt_settings_widget.setMinimumSize(QtCore.QSize(0, 120))
        self.opt_settings_widget.setObjectName("opt_settings_widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.opt_settings_widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_52 = QtWidgets.QLabel(self.opt_settings_widget)
        self.label_52.setObjectName("label_52")
        self.gridLayout_9.addWidget(self.label_52, 0, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.opt_settings_widget)
        self.label_54.setObjectName("label_54")
        self.gridLayout_9.addWidget(self.label_54, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(849, 78, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 2, 3, 1)
        self.init_view_check = QtWidgets.QCheckBox(self.opt_settings_widget)
        self.init_view_check.setObjectName("init_view_check")
        self.gridLayout_9.addWidget(self.init_view_check, 0, 3, 1, 1)
        self.opt_mov_spin = QtWidgets.QSpinBox(self.opt_settings_widget)
        self.opt_mov_spin.setObjectName("opt_mov_spin")
        self.gridLayout_9.addWidget(self.opt_mov_spin, 1, 0, 1, 1)
        self.alpha_spin = QtWidgets.QDoubleSpinBox(self.opt_settings_widget)
        self.alpha_spin.setObjectName("alpha_spin")
        self.gridLayout_9.addWidget(self.alpha_spin, 1, 1, 1, 1)
        self.dest_view_check = QtWidgets.QCheckBox(self.opt_settings_widget)
        self.dest_view_check.setObjectName("dest_view_check")
        self.gridLayout_9.addWidget(self.dest_view_check, 1, 3, 2, 1)
        self.label_53 = QtWidgets.QLabel(self.opt_settings_widget)
        self.label_53.setObjectName("label_53")
        self.gridLayout_9.addWidget(self.label_53, 2, 0, 1, 1)
        self.opt_frame_spin = QtWidgets.QSpinBox(self.opt_settings_widget)
        self.opt_frame_spin.setObjectName("opt_frame_spin")
        self.gridLayout_9.addWidget(self.opt_frame_spin, 3, 0, 1, 1)
        self.src_view_check = QtWidgets.QCheckBox(self.opt_settings_widget)
        self.src_view_check.setObjectName("src_view_check")
        self.gridLayout_9.addWidget(self.src_view_check, 3, 3, 1, 1)
        self.verticalLayout_8.addWidget(self.opt_settings_widget)
        self.verticalLayout_7.addWidget(self.opt_widget)
        self.tabs.addTab(self.opt_tab, "")
        self.verticalLayout_5.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DipteraTrack"))
        self.label.setText(_translate("MainWindow", "Select session folder:"))
        self.label_3.setText(_translate("MainWindow", "Session parameters"))
        self.label_2.setText(_translate("MainWindow", "Session folder:"))
        self.ses_folder_label.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Background folder:"))
        self.bckg_folder_label.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Calibration folder:"))
        self.cal_folder_label.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "Movie folders:"))
        self.mov_folder1_label.setText(_translate("MainWindow", "..."))
        self.mov_folder2_label.setText(_translate("MainWindow", "..."))
        self.mov_folder3_label.setText(_translate("MainWindow", "..."))
        self.mov_folder4_label.setText(_translate("MainWindow", "..."))
        self.mov_folder5_label.setText(_translate("MainWindow", "..."))
        self.mov_folder6_label.setText(_translate("MainWindow", "..."))
        self.mov_folder7_label.setText(_translate("MainWindow", "..."))
        self.mov_folder8_label.setText(_translate("MainWindow", "..."))
        self.label_18.setText(_translate("MainWindow", "Camera folders:"))
        self.cam_folder1_label.setText(_translate("MainWindow", "..."))
        self.cam_folder2_label.setText(_translate("MainWindow", "..."))
        self.cam_folder3_label.setText(_translate("MainWindow", "..."))
        self.cam_folder4_label.setText(_translate("MainWindow", "..."))
        self.ses_folder_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.bckg_folder_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cal_folder_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder1_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder2_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder3_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder4_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder5_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder6_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder7_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mov_folder8_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder1_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder2_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder3_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder4_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder5_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder6_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.cam_folder5_label.setText(_translate("MainWindow", "..."))
        self.cam_folder6_label.setText(_translate("MainWindow", "..."))
        self.label_25.setText(_translate("MainWindow", "Frame name:"))
        self.frame_name_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.frame_name_label.setText(_translate("MainWindow", "..."))
        self.label_27.setText(_translate("MainWindow", "Background image format:"))
        self.label_28.setText(_translate("MainWindow", "Calibration image format:"))
        self.label_29.setText(_translate("MainWindow", "Frame image format:"))
        self.label_30.setText(_translate("MainWindow", "Trigger settings"))
        self.label_31.setText(_translate("MainWindow", "start frame nr:"))
        self.label_32.setText(_translate("MainWindow", "trigger frame nr:"))
        self.label_33.setText(_translate("MainWindow", "end frame nr:"))
        self.label_34.setText(_translate("MainWindow", "Trigger mode:"))
        self.label_4.setText(_translate("MainWindow", "Model settings"))
        self.mdl_loc_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mdl_loc_label.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Model location:"))
        self.label_11.setText(_translate("MainWindow", "Model name:"))
        self.mdl_name_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.mdl_name_label.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Calibration file:"))
        self.cal_file_label.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Session name:"))
        self.ses_name_label.setText(_translate("MainWindow", "..."))
        self.reset_selection_push_btn.setText(_translate("MainWindow", "reset selection"))
        self.start_session_push_btn.setText(_translate("MainWindow", "start session"))
        self.save_settings_push_btn.setText(_translate("MainWindow", "save parameter file"))
        self.load_settings_file_label.setText(_translate("MainWindow", "..."))
        self.load_settings_push_btn.setText(_translate("MainWindow", "load parameter file"))
        self.load_settings_rbtn.setText(_translate("MainWindow", "RadioButton"))
        self.tabs.setTabText(self.tabs.indexOf(self.ses_par_tab), _translate("MainWindow", "Movie selection"))
        self.label_16.setText(_translate("MainWindow", "Voxel grid parameters:"))
        self.label_12.setText(_translate("MainWindow", "Nx:"))
        self.label_13.setText(_translate("MainWindow", "Ny:"))
        self.label_14.setText(_translate("MainWindow", "Nz:"))
        self.label_15.setText(_translate("MainWindow", "ds:"))
        self.label_17.setText(_translate("MainWindow", "x0:"))
        self.label_19.setText(_translate("MainWindow", "y0:"))
        self.label_20.setText(_translate("MainWindow", "z0:"))
        self.calc_vox_btn.setText(_translate("MainWindow", "calculate voxel grid"))
        self.label_49.setText(_translate("MainWindow", "Camera parameters:"))
        self.label_50.setText(_translate("MainWindow", "pixel size (mm):"))
        self.tabs.setTabText(self.tabs.indexOf(self.focal_grid_tab), _translate("MainWindow", "Voxel grid"))
        self.label_22.setText(_translate("MainWindow", "Movie nr:"))
        self.load_scale_btn.setText(_translate("MainWindow", "load model scale"))
        self.save_scale_btn.setText(_translate("MainWindow", "save model scale"))
        self.set_model_btn.setText(_translate("MainWindow", "set model scale"))
        self.label_21.setText(_translate("MainWindow", "Frame:"))
        self.tabs.setTabText(self.tabs.indexOf(self.model_scale_tab), _translate("MainWindow", "Scale model"))
        self.label_23.setText(_translate("MainWindow", "Model parameters:"))
        self.tabs.setTabText(self.tabs.indexOf(self.model_view_tab), _translate("MainWindow", "Model view"))
        self.label_40.setText(_translate("MainWindow", "movie nr:"))
        self.label_24.setText(_translate("MainWindow", "frame:"))
        self.label_26.setText(_translate("MainWindow", "body threshold"))
        self.label_35.setText(_translate("MainWindow", "wing threshold"))
        self.label_36.setText(_translate("MainWindow", "sigma"))
        self.label_37.setText(_translate("MainWindow", "K"))
        self.label_38.setText(_translate("MainWindow", "min body area"))
        self.label_39.setText(_translate("MainWindow", "min wing area"))
        self.label_43.setText(_translate("MainWindow", "Set image mask:"))
        self.label_44.setText(_translate("MainWindow", "cam nr:"))
        self.label_45.setText(_translate("MainWindow", "segment nr:"))
        self.seg_update_btn.setText(_translate("MainWindow", "update"))
        self.add_mask_btn.setText(_translate("MainWindow", "add to mask"))
        self.reset_mask_btn.setText(_translate("MainWindow", "reset"))
        self.continue_btn.setText(_translate("MainWindow", "continue"))
        self.tabs.setTabText(self.tabs.indexOf(self.segment_tab), _translate("MainWindow", "Segmentation"))
        self.label_41.setText(_translate("MainWindow", "movie nr:"))
        self.tethered_radio_btn.setText(_translate("MainWindow", "tethered flight"))
        self.free_radio_btn.setText(_translate("MainWindow", "free flight"))
        self.label_47.setText(_translate("MainWindow", "stroke angle bound:"))
        self.label_51.setText(_translate("MainWindow", "wing pitch angle bound:"))
        self.pcl_view_btn.setText(_translate("MainWindow", "pcl view"))
        self.bbox_view_btn.setText(_translate("MainWindow", "bbox view"))
        self.model_view_btn.setText(_translate("MainWindow", "model view"))
        self.label_42.setText(_translate("MainWindow", "frame nr:"))
        self.label_48.setText(_translate("MainWindow", "deviation angle bound:"))
        self.label_46.setText(_translate("MainWindow", "sphere radius:"))
        self.tabs.setTabText(self.tabs.indexOf(self.pcl_view_tab), _translate("MainWindow", "Pointcloud view"))
        self.label_52.setText(_translate("MainWindow", "movie nr:"))
        self.label_54.setText(_translate("MainWindow", "alpha:"))
        self.init_view_check.setText(_translate("MainWindow", "initial state"))
        self.dest_view_check.setText(_translate("MainWindow", "destination contour"))
        self.label_53.setText(_translate("MainWindow", "frame nr:"))
        self.src_view_check.setText(_translate("MainWindow", "source contour"))
        self.tabs.setTabText(self.tabs.indexOf(self.opt_tab), _translate("MainWindow", "Contour optimization"))

from BoundingBoxWidget import BBoxWidget
from ContourViewWidget import ContourViewWidget
from ImageSegmentWidget import ImageSegmentWidget
from ModelViewWidget import ModelViewWidget
from ScaleModelWidget import ScaleModelWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

