#include <boost/python.hpp>
#include <boost/python/numpy.hpp>
#include <boost/python/call.hpp>
#include "flight_tracker_class.h"

namespace p = boost::python;
namespace np = boost::python::numpy;

BOOST_PYTHON_MODULE(FlightTracker_lib)
{
	Py_Initialize();
	np::initialize();
	p::class_<FLT>("FLT")
		.def("set_session_loc", &FLT::SetSessionLocation)
		.def("set_backgroud_subtract", &FLT::SetBackgroundSubtraction)
		.def("set_calibration", &FLT::SetCalibrationParameters)
		.def("set_movie_list", &FLT::SetMovieList)
		.def("set_cam_list", &FLT::SetCamList)
		.def("set_frame_par", &FLT::SetFrameParameters)
		.def("set_model_par", &FLT::SetModelParameters)
		.def("set_trigger_par", &FLT::SetTriggerParameters)
		.def("set_session_par", &FLT::SetSessionParameters)
		.def("display_session_par", &FLT::PrintSessionParameters)
		.def("set_frame_loader", &FLT::SetFrameLoader)
		.def("get_image_size", &FLT::ReturnImageSize)
		.def("load_frame", &FLT::LoadFrame)
		.def("return_frame", &FLT::ReturnFrame)
		.def("set_focal_grid", &FLT::SetFocalGrid)
		.def("set_pixel_size", &FLT::SetPixelSizeCamera)
		.def("display_focal_grid_par", &FLT::PrintFocalGridParameters)
		.def("calc_focal_grid", &FLT::CalculateFocalGrid)
		.def("xyz_2_uv", &FLT::XYZ2UV)
		.def("drag_point_3d", &FLT::DragPoint3D)
		.def("load_model", &FLT::LoadModel)
		.def("get_stl_list", &FLT::ReturnSTLList)
		.def("get_start_state", &FLT::StartState)
		.def("drag_pt_labels", &FLT::ReturnPointLabels)
		.def("drag_pt_symbols", &FLT::ReturnPointSymbols)
		.def("drag_pt_colors", &FLT::ReturnPointColors)
		.def("drag_pt_start", &FLT::ReturnPointStartPos)
		.def("drag_ln_connect", &FLT::ReturnLineConnectivity)
		.def("drag_ln_colors", &FLT::ReturnLineColors)
		.def("drag_scale_texts", &FLT::ReturnScaleTexts)
		.def("drag_scale_calc", &FLT::ReturnScaleCalc)
		.def("drag_length_calc", &FLT::ReturnLengthCalc)
		.def("drag_origin_ind", &FLT::ReturnOriginInd)
		.def("drag_contour_calc", &FLT::ReturnContourCalc)
		.def("set_body_length", &FLT::SetBodyLength)
		.def("set_wing_length", &FLT::SetWingLength)
		.def("set_stroke_bound", &FLT::SetStrokeBounds)
		.def("set_deviation_bound", &FLT::SetDeviationBounds)
		.def("set_wing_pitch_bound", &FLT::SetWingPitchBounds)
		.def("set_model_scale", &FLT::SetModelScales)
		.def("get_model_scale", &FLT::GetModelScales)
		.def("set_model_origin", &FLT::SetOrigin)
		.def("set_neck_loc", &FLT::SetNeckLoc)
		.def("set_joint_L_loc", &FLT::SetJointLeftLoc)
		.def("set_joint_R_loc", &FLT::SetJointRightLoc)
		.def("set_fixed_body_points", &FLT::SetFixedBodyPoints)
		.def("segment_frame", &FLT::SegmentFrame)
		.def("set_seg_param", &FLT::SetImagSegmParam)
		.def("set_mask", &FLT::SegImageMask)
		.def("reset_mask", &FLT::ResetImageMask)
		.def("set_min_nr_points", &FLT::SetMinimumNumberOfPoints)
		.def("set_min_conn_points", &FLT::SetMinimumConnectionPoints)
		.def("set_sphere_radius", &FLT::SetSphereRadius)
		.def("set_tethered_flight", &FLT::SetTetheredFlight)
		.def("find_initial_state", &FLT::FindInitialState)
		.def("get_initial_state", &FLT::GetInitState)
		.def("return_wingtip_boxes", &FLT::ReturnWingtipBoxes)
		.def("return_wingtip_pcls", &FLT::ReturnWingtipPCLS)
		.def("return_seg_frame", &FLT::ReturnSegmentedFrame)
		.def("project_frame_2_pcl", &FLT::ProjectFrame2PCL)
		.def("return_seg_pcl", &FLT::ReturnSegPCL)
		.def("return_fixed_joints", &FLT::ReturnFixedJointLocs)
		.def("return_SRF_orientation", &FLT::ReturnSRFOrientation)
		.def("return_dest_contour", &FLT::ReturnDestContour)
		.def("return_init_contour", &FLT::ReturnInitContour)
		.def("return_outer_contour", &FLT::ReturnOuterContour);
}